#!/usr/bin/env python3
"""Generate the owner-sync questionnaire from the flock DB (plan Phase 0).

Soli Deo Gloria.

Builds admin/OWNER-SYNC-QUESTIONNAIRE.md from data/flock_database.json so Ken can
answer everything only he knows in one sitting instead of forty interruptions.
Sections: suspect bulk-cleanup status_dates (Helene-first per directive), alive
animals with no pen (grouped for a pen census), [UNCLEAR] markers, low-confidence
records, and the standing open follow-ups. Regenerate any time — the file is
derived, the DB is SSOT; answers get applied to the DB (validate_flock-gated),
never edited into this file.
"""
import json
import re
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
DB_PATH = REPO_ROOT / "data" / "flock_database.json"
OUT_PATH = REPO_ROOT / "admin" / "OWNER-SYNC-QUESTIONNAIRE.md"

SUSPECT_DATES = {"2026-04-02", "2026-04-06"}


def label(s):
    tag = s.get("tag")
    return f"**{s.get('name') or s['id']}**" + (f" (tag {tag})" if tag else "") + f" — `{s['id']}`"


def main():
    db = json.load(open(DB_PATH))
    sheep = db.get("sheep", [])
    lines = [
        "<!-- Soli Deo Gloria. Generated by scripts/owner_sync_questionnaire.py — DO NOT hand-edit; ",
        "     answers go into the DB via validated commits, then regenerate. -->",
        "",
        "# Owner-Sync Questionnaire (plan Phase 0)",
        "",
        f"Generated from `data/flock_database.json` ({len(sheep)} records). One sitting, checkboxes",
        "and blanks — anything you skip stays honestly unknown in the DB rather than guessed.",
        "",
        "Standing rules applied: bulk-cleanup dates are placeholders, never real (ask-first);",
        "Helene 2024-09-26 is the default hypothesis for stale deceased records; owner testimony",
        "overrides everything.",
        "",
    ]

    # 1. Suspect status_dates
    susp = [s for s in sheep if s.get("status_date") in SUSPECT_DATES]
    lines += [f"## 1. Bulk-cleanup placeholder dates — {len(susp)} records need the real date/cause",
              "",
              "For each: real date (or closest you know) and cause. `Helene` = 2024-09-26.",
              ""]
    by_status = defaultdict(list)
    for s in susp:
        by_status[s.get("status", "?")].append(s)
    for st in sorted(by_status):
        lines.append(f"### status: {st} ({len(by_status[st])})")
        lines.append("")
        for s in sorted(by_status[st], key=lambda x: x["id"]):
            if st == "alive":
                lines.append(f"- [ ] {label(s)} — placeholder `{s.get('status_date')}` on an ALIVE record → "
                             f"status correct? ___ · real event date if any: ______")
            else:
                lines.append(f"- [ ] {label(s)} — placeholder `{s.get('status_date')}` → real date: ______ · cause: ______")
        lines.append("")

    # 2. Pen census
    alive = [s for s in sheep if s.get("status") == "alive"]
    no_pen = sorted((s for s in alive if not s.get("pen")), key=lambda x: x["id"])
    lines += [f"## 2. Pen census — {len(no_pen)} of {len(alive)} living animals have no pen recorded",
              "",
              "Walk order is yours; write the pen next to each (or 'sold'/'deceased' if the status is wrong).",
              ""]
    for s in no_pen:
        sex = s.get("sex", "?")
        lines.append(f"- [ ] {label(s)} ({sex}) → pen: ______")
    lines.append("")

    # 3. [UNCLEAR] markers
    unclear = [(s, m) for s in sheep for m in re.findall(r"[^.|]*\[UNCLEAR\][^.|]*", json.dumps(s))]
    lines += [f"## 3. [UNCLEAR] markers — {len(unclear)}",
              ""]
    for s, frag in unclear:
        frag = frag.strip().replace("\\\"", "'")[:160]
        lines.append(f"- [ ] {label(s)}: …{frag}… → answer: ______")
    lines.append("")

    # 4. Low-confidence records
    low = sorted((s for s in sheep if s.get("confidence") == "low" and s.get("status") == "alive"),
                 key=lambda x: x["id"])
    lines += [f"## 4. Low-confidence LIVING records — {len(low)} (owner confirmation upgrades them)",
              ""]
    for s in low:
        lines.append(f"- [ ] {label(s)} — confirm identity/status/pen as recorded? yes / corrections: ______")
    lines.append("")

    # 5. Standing follow-ups (from HLS open tasks — kept short, ids for traceability).
    # 2026-08-19 owner sync applied: channel=Atlas PWA push · coords=western coastal Pasco ·
    # Lara FAMACHA 2 · Buck-original=Helene drowning · pen moves confirmed · Centralia=
    # background-only · feed cost $0.31/head/day · 2222=$600, Angus=$250 recorded.
    lines += [
        "## 5. Standing follow-ups (open HLS tasks)",
        "",
        "- [ ] WHICH ONE SOLD? You answered 'sold I believe' to a question that covered TWO animals — Kaladin (ram, tag 014) and Orange Tag 31 Ewe. Kaladin sold? ___ · Orange Tag 31 sold? ___ (both records currently say alive, no pen)",
        "- [ ] TWO BUCKS, ONE RECORD: Buck-original now carries your Helene death (2024-09-26, drowned, freezer) — but FAMACHA + CDT checks dated Feb–Mar 2026 sit on his record from the 2026-05-14 merge. Were those 2026 checks actually on current Buck (his brother, Pen 6)? yes / no / unsure: ______",
        "- [ ] GIGI = GG? You said 'Gigi and her sister were around $500' — is Gigi the ewe recorded as GG (tag MC-19, Pen 4)? ___ · and who is her sister (name/tag)? ______ (their $500 stays unapplied until the records are certain)",
        "- [ ] BREEDING PIPELINE SEED (MCS-17): the ram-in dates you said you'd dig up — (ram, pen, date in, date out-or-still-in), one line each. These become the matings table and drive preg-check/due/lambing-watch dates.",
        "- [ ] LAMB MARKET PRICE (MCS-24): you weren't sure — when you next see a sale sheet: $___/lb. (Feed side is done: $0.31/head/day recorded.)",
        "- [ ] SHELF COUNTS (MCS-25): you named what's on hand — now just quantity + expiry off each label: ivermectin ___ exp ___ · iron ___ exp ___ · Prohibit ___ exp ___ · vitamin B ___ exp ___ · dexamethasone ___ exp ___ · antibiotics (which + how much) ______",
        "- [ ] CARD SCANS (the 43 dates): the scans in the repo are the most-current source and I'll transcribe them (`mcs-card-scans-date-transcription`) — nothing needed from you unless I hit a note I can't read; those will come back as specific photos with questions.",
        "- [ ] PEN CENSUS: open app/census.html on your phone — tap a pen (or Sold/Deceased) per animal, hit Export, text me the block. Progress saves on the phone.",
        "",
        "**Soli Deo Gloria.** Answers get applied through validated commits; regenerate this file after.",
    ]

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_PATH} — sections: {len(susp)} suspect dates, {len(no_pen)} pen census, "
          f"{len(unclear)} UNCLEAR, {len(low)} low-confidence")


if __name__ == "__main__":
    main()
