#!/usr/bin/env python3
"""Generate the owner-sync questionnaire from the flock DB (plan Phase 0).

Soli Deo Gloria.

Builds admin/OWNER-SYNC-QUESTIONNAIRE.md from data/flock_database.json so Ken can
answer everything only he knows in one sitting instead of forty interruptions.
Sections: suspect bulk-cleanup status_dates (Helene-first per directive), alive
animals with no pen (grouped for a pen census), [UNCLEAR] markers, low-confidence
records, and the standing open follow-ups. Regenerate any time — the file is
derived, the DB is SSOT; answers get applied to the DB (validate_flock-gated),
never edited into this file.
"""
import json
import re
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
DB_PATH = REPO_ROOT / "data" / "flock_database.json"
OUT_PATH = REPO_ROOT / "admin" / "OWNER-SYNC-QUESTIONNAIRE.md"

SUSPECT_DATES = {"2026-04-02", "2026-04-06"}


def label(s):
    tag = s.get("tag")
    return f"**{s.get('name') or s['id']}**" + (f" (tag {tag})" if tag else "") + f" — `{s['id']}`"


def main():
    db = json.load(open(DB_PATH))
    sheep = db.get("sheep", [])
    lines = [
        "<!-- Soli Deo Gloria. Generated by scripts/owner_sync_questionnaire.py — DO NOT hand-edit; ",
        "     answers go into the DB via validated commits, then regenerate. -->",
        "",
        "# Owner-Sync Questionnaire (plan Phase 0)",
        "",
        f"Generated from `data/flock_database.json` ({len(sheep)} records). One sitting, checkboxes",
        "and blanks — anything you skip stays honestly unknown in the DB rather than guessed.",
        "",
        "Standing rules applied: bulk-cleanup dates are placeholders, never real (ask-first);",
        "Helene 2024-09-26 is the default hypothesis for stale deceased records; owner testimony",
        "overrides everything.",
        "",
    ]

    # 1. Suspect status_dates
    susp = [s for s in sheep if s.get("status_date") in SUSPECT_DATES]
    lines += [f"## 1. Bulk-cleanup placeholder dates — {len(susp)} records need the real date/cause",
              "",
              "For each: real date (or closest you know) and cause. `Helene` = 2024-09-26.",
              ""]
    by_status = defaultdict(list)
    for s in susp:
        by_status[s.get("status", "?")].append(s)
    for st in sorted(by_status):
        lines.append(f"### status: {st} ({len(by_status[st])})")
        lines.append("")
        for s in sorted(by_status[st], key=lambda x: x["id"]):
            if st == "alive":
                lines.append(f"- [ ] {label(s)} — placeholder `{s.get('status_date')}` on an ALIVE record → "
                             f"status correct? ___ · real event date if any: ______")
            else:
                lines.append(f"- [ ] {label(s)} — placeholder `{s.get('status_date')}` → real date: ______ · cause: ______")
        lines.append("")

    # 2. Pen census
    alive = [s for s in sheep if s.get("status") == "alive"]
    no_pen = sorted((s for s in alive if not s.get("pen")), key=lambda x: x["id"])
    lines += [f"## 2. Pen census — {len(no_pen)} of {len(alive)} living animals have no pen recorded",
              "",
              "Walk order is yours; write the pen next to each (or 'sold'/'deceased' if the status is wrong).",
              ""]
    for s in no_pen:
        sex = s.get("sex", "?")
        lines.append(f"- [ ] {label(s)} ({sex}) → pen: ______")
    lines.append("")

    # 3. [UNCLEAR] markers
    unclear = [(s, m) for s in sheep for m in re.findall(r"[^.|]*\[UNCLEAR\][^.|]*", json.dumps(s))]
    lines += [f"## 3. [UNCLEAR] markers — {len(unclear)}",
              ""]
    for s, frag in unclear:
        frag = frag.strip().replace("\\\"", "'")[:160]
        lines.append(f"- [ ] {label(s)}: …{frag}… → answer: ______")
    lines.append("")

    # 4. Low-confidence records
    low = sorted((s for s in sheep if s.get("confidence") == "low" and s.get("status") == "alive"),
                 key=lambda x: x["id"])
    lines += [f"## 4. Low-confidence LIVING records — {len(low)} (owner confirmation upgrades them)",
              ""]
    for s in low:
        lines.append(f"- [ ] {label(s)} — confirm identity/status/pen as recorded? yes / corrections: ______")
    lines.append("")

    # 5. Standing follow-ups (from HLS open tasks — kept short, ids for traceability)
    lines += [
        "## 5. Standing follow-ups (open HLS tasks)",
        "",
        "- [ ] Pen moves planned 2026-05-14 — done in the field? Buck→Pen 6 ___ · Rocky tag140→Tree Fort ___ · MC08→auction ___ (`mcs-pen-moves-pending`)",
        "- [ ] Buck-original: real death date/cause, or still possibly alive? (`mc-buck-original-death-date-2026-05-14`)",
        "- [ ] Kaladin's current pen (`mc-kaladin-current-pen-2026-04-26`)",
        "- [ ] Orange Tag 31 Ewe — where is she now? (`open-follow-up-orange-tag-31-ewe-location-2026-05-14`)",
        "- [ ] Centralia records: 8 image attachments still pending upload (`mcs-centralia-image-attachments`)",
        "- [ ] 'Lara is on' (2026-08-18) — on the mend, or on treatment herself?",
        "- [ ] WEATHER SIGNAL (MCS-1): farm coordinates for data/farm_location.json — lat: ______ lon: ______ (approximate is fine; drives the warm-wet recheck tightening)",
        "- [ ] BREEDING PIPELINE SEED (MCS-17): for each pen with a ram — when did the ram go in? (ram, pen, date in, date out-or-still-in). One line each; these become the matings table and drive preg-check/due/lambing-watch dates.",
        "- [ ] ECONOMICS SEED (MCS-13/24): purchase prices for bought-in animals you remember (animal: $___), sale proceeds so far this year (animal/date/$ or auction batch), and current market price per lb for lambs: $___/lb · feed cost per head per day: $___ (rough is fine — the hold-vs-sell calculator refuses to run on guesses I invent, but runs on yours).",
        "- [ ] INVENTORY COUNT (MCS-25): shelf count of the barn cabinet — wormers, vaccines, feed on hand (item / quantity / expiry date off the label / when-to-reorder). The expiry+reorder alerts start the day this is entered.",
        "- [ ] REMINDER CHANNEL (MCS-2): the agenda now serves at Atlas `/api/flock/agenda` — where should proactive nudges land so you actually see them? text / ntfy app / email / Atlas assistant: ______ (`mcs-push-reminders-delivery`)",
        "",
        "**Soli Deo Gloria.** Answers get applied through validated commits; regenerate this file after.",
    ]

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_PATH} — sections: {len(susp)} suspect dates, {len(no_pen)} pen census, "
          f"{len(unclear)} UNCLEAR, {len(low)} low-confidence")


if __name__ == "__main__":
    main()
